const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const defaults={theme:'neon',autopilot:true,apiBase:'',style:'Balanced',networth:50000,drawdown:18,singleCap:28,risk:46,lessRiskClicks:0,samples:18,portfolio:{cash:5100,BTC:{qty:.145,price:61200},ETH:{qty:2.35,price:2650},SOL:{qty:24,price:145}},circles:[{name:'Macro + BTC',members:218,style:'Research only'},{name:'Builder Portfolio',members:83,style:'Paper portfolio'},{name:'DeFi Radar',members:146,style:'Shared watchlist'}],signals:[]};
let state=Object.assign({},defaults,JSON.parse(localStorage.getItem('cryptopilot')||'{}'));state.portfolio={...defaults.portfolio,...state.portfolio};state.circles=state.circles||defaults.circles;state.signals=state.signals||[];
const save=()=>localStorage.setItem('cryptopilot',JSON.stringify(state));
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);
const portfolioValue=()=>state.portfolio.cash+['BTC','ETH','SOL'].reduce((a,c)=>a+state.portfolio[c].qty*state.portfolio[c].price,0);
const allocation=c=>(c==='USDC'?state.portfolio.cash:state.portfolio[c].qty*state.portfolio[c].price)/portfolioValue()*100;
function render(){document.body.classList.toggle('theme-akatsuki',state.theme==='akatsuki');$('#themeBtn').textContent=`Theme: ${state.theme==='akatsuki'?'Akatsuki':'Neon'}`;$('#autoState').textContent=state.autopilot?'ON':'OFF';$('#autoState').className=state.autopilot?'green':'red';$('#portfolioValue').textContent=money(portfolioValue());$('#riskLabel').textContent=`${state.risk<35?'Conservative':state.risk>66?'Aggressive':'Balanced'} · ${state.risk}`;$('#cashReserve').textContent=`${allocation('USDC').toFixed(0)}%`;$('#samples').textContent=state.samples;$('#style').value=state.style;$('#networth').value=String(state.networth);$('#drawdown').value=state.drawdown;$('#singleCap').value=state.singleCap;$('#apiBase').value=state.apiBase||'';renderAssets();renderSignals();renderRisk();renderCircles();renderExchanges()}
function renderAssets(){const items=['BTC','ETH','SOL','USDC'];$('#assets').innerHTML=items.map(c=>{const val=c==='USDC'?state.portfolio.cash:state.portfolio[c].qty*state.portfolio[c].price;const p=allocation(c),px=c==='USDC'?1:state.portfolio[c].price;return `<div class="asset"><div><span class="coin">${c}</span><div class="muted">${c==='USDC'?'Cash reserve':money(px)}</div></div><b>${money(val)}</b><div>${p.toFixed(1)}%</div><div class="bar"><i style="width:${Math.min(100,p*2.2)}%"></i></div></div>`}).join('')}
function calculateRisk(){state.style=$('#style').value;state.networth=Number($('#networth').value);state.drawdown=Number($('#drawdown').value);state.singleCap=Number($('#singleCap').value);let base={Conservative:27,Balanced:50,Aggressive:72}[state.style];base+=(state.drawdown-18)*.65;base+=(state.singleCap-28)*.35;if(state.networth<20000)base-=6;if(state.networth>500000)base+=3;base-=state.lessRiskClicks*4;state.risk=Math.max(15,Math.min(82,Math.round(base)));state.samples++;save();render()}
function renderRisk(){const cashFloor=Math.max(8,Math.round(30-state.risk*.25));const trade=Math.max(.5,(state.risk/25).toFixed(1));$('#riskRules').innerHTML=`<div class="signal"><strong>Cash floor: ${cashFloor}%</strong><span class="muted">Autopilot will not intentionally rebalance below this reserve.</span></div><div class="signal"><strong>Single asset cap: ${state.singleCap}%</strong><span class="muted">Learned preferences cannot override this hard cap.</span></div><div class="signal"><strong>Typical new position: ≤ ${trade}%</strong><span class="muted">Higher volatility or weaker evidence reduces sizing.</span></div><div class="signal"><strong>Daily circuit breaker</strong><span class="muted">Pause new risk after abnormal drawdown, stale prices or exchange/API errors.</span></div>`}
async function price(coin){try{const r=await fetch(`https://api.coinbase.com/v2/prices/${coin}-USD/spot`);if(!r.ok)throw 0;const j=await r.json();return Number(j.data.amount)}catch{return null}}
async function refreshPrices(){$('#priceStatus').textContent='Refreshing prices…';const vals=await Promise.all(['BTC','ETH','SOL'].map(price));['BTC','ETH','SOL'].forEach((c,i)=>{if(vals[i])state.portfolio[c].price=vals[i]});save();renderAssets();$('#portfolioValue').textContent=money(portfolioValue());$('#priceStatus').textContent=vals.filter(Boolean).length?'Live Coinbase spot':'Demo prices'}
const demoNews=[['BTC','Institutional demand remains constructive while volatility compresses',.74],['ETH','Protocol activity improves but momentum is mixed',.57],['SOL','Strong activity, elevated short-term volatility',.68],['BTC','Macro uncertainty argues for smaller position sizing',-.28]];
function scan(){state.signals=demoNews.map(([coin,text,sent])=>{const confidence=Math.round(55+Math.abs(sent)*38),action=sent>.65&&state.risk>35?'Paper buy':sent<-.5?'Reduce risk':'Hold / watch';return{coin,text,sent,confidence,action,time:new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}});state.samples+=state.signals.length;const avg=state.signals.reduce((a,s)=>a+s.sent,0)/state.signals.length,posture=Math.round(50+avg*28);$('#posture').textContent=`${posture} / 100`;$('#postureLabel').textContent=posture>62?'Measured bullish':posture<43?'Defensive':'Neutral';$('#postureWhy').textContent='Signals are advisory until they pass portfolio limits, price confirmation and the risk constitution.';save();renderSignals()}
function renderSignals(){if(!state.signals.length)state.signals=[{coin:'BTC',text:'Waiting for the next market/news scan.',sent:.1,confidence:58,action:'Watch',time:'now'}];$('#signals').innerHTML=state.signals.map(s=>`<div class="signal"><div class="row between"><strong>${s.coin} · ${s.action}</strong><span class="${s.sent>=0?'green':'red'}">${s.confidence}%</span></div><span class="muted">${s.text}</span><div class="muted" style="font-size:11px;margin-top:5px">${s.time}</div></div>`).join('')}
function renderCircles(){$('#circles').innerHTML=state.circles.map((c,i)=>`<div class="exchange"><div><strong>${c.name}</strong><div class="muted">${c.style} · ${c.members} members</div></div><button class="btn" data-join="${i}">Join</button></div>`).join('');$$('[data-join]').forEach(b=>b.onclick=()=>{state.circles[+b.dataset.join].members++;save();renderCircles()})}
function renderExchanges(){const xs=[['Coinbase','JWT / Advanced Trade'],['Binance','HMAC / Spot + Testnet'],['Kraken','HMAC / REST + WebSocket'],['Robinhood Crypto','Ed25519 API · US-only'],['0x DEX','API quote + user wallet signature']];$('#exchanges').innerHTML=xs.map(x=>`<div class="exchange"><div><strong><span class="dot ${state.apiBase?'ok':''}"></span>${x[0]}</strong><div class="muted">${x[1]}</div></div><button class="btn connect" data-ex="${x[0]}">${state.apiBase?'Check':'Setup'}</button></div>`).join('');$$('.connect').forEach(b=>b.onclick=()=>checkExchange(b.dataset.ex))}
async function checkExchange(name){if(!state.apiBase)return alert('Add the deployed Worker URL first.');try{const r=await fetch(`${state.apiBase.replace(/\/$/,'')}/api/connectors`),j=await r.json();alert(`${name}: ${JSON.stringify(j.connectors?.[name]||j)}`)}catch{alert('Backend not reachable yet. Demo/paper mode remains available.')}}
function botReply(q){const p=q.trim().split(/\s+/);if(q==='/risk')return `Adaptive risk is ${state.risk}/100 with a ${state.singleCap}% single-asset cap.`;if(q==='/portfolio')return `Paper portfolio ${money(portfolioValue())}; cash reserve ${allocation('USDC').toFixed(0)}%.`;if(q==='/pause'){state.autopilot=false;save();render();return 'Autopilot paused.'}if(q==='/resume'){state.autopilot=true;save();render();return 'Autopilot resumed in paper mode.'}if(p[0]==='/theme'){state.theme=(p[1]||'').toLowerCase()==='akatsuki'?'akatsuki':'neon';save();render();return `Theme set to ${state.theme}.`}if(p[0]==='/paper-buy'&&['BTC','ETH','SOL'].includes((p[1]||'').toUpperCase())){const c=p[1].toUpperCase(),amt=Math.min(Number(p[2])||0,state.portfolio.cash);if(amt<=0)return 'Enter a positive USD amount.';if(allocation(c)+amt/portfolioValue()*100>state.singleCap)return `Blocked: ${c} would exceed your ${state.singleCap}% cap.`;state.portfolio.cash-=amt;state.portfolio[c].qty+=amt/state.portfolio[c].price;state.samples++;save();render();return `Paper bought ${money(amt)} of ${c}.`}return 'Commands: /risk, /portfolio, /pause, /resume, /paper-buy BTC 100, /theme akatsuki'}
function addChat(text,me=false){$('#chat').insertAdjacentHTML('beforeend',`<div class="bubble ${me?'me':''}">${text}</div>`);$('#chat').scrollTop=$('#chat').scrollHeight}
$$('.tab').forEach(t=>t.onclick=()=>{$$('.tab').forEach(x=>x.classList.remove('active'));t.classList.add('active');$$('.panel').forEach(x=>x.classList.remove('active'));$('#'+t.dataset.tab).classList.add('active')});
$('#themeBtn').onclick=()=>{state.theme=state.theme==='akatsuki'?'neon':'akatsuki';save();render()};$('#killBtn').onclick=()=>{state.autopilot=false;save();render();alert('Emergency stop engaged. New automated orders are blocked by the UI state.')};$('#scanBtn').onclick=scan;$('#learnBtn').onclick=calculateRisk;$('#feedbackBtn').onclick=()=>{state.lessRiskClicks++;calculateRisk()};$('#createCircle').onclick=()=>{const name=$('#circleName').value.trim();if(!name)return;state.circles.push({name,members:1,style:$('#circleStyle').value});$('#circleName').value='';save();renderCircles()};$('#saveApi').onclick=()=>{state.apiBase=$('#apiBase').value.trim();save();renderExchanges();alert('Backend URL saved locally.')};$('#sendBot').onclick=()=>{const q=$('#botInput').value.trim();if(!q)return;addChat(q,true);addChat(botReply(q));$('#botInput').value=''};$('#botInput').addEventListener('keydown',e=>{if(e.key==='Enter')$('#sendBot').click()});$$('.pay').forEach(b=>b.onclick=async()=>{const plan=b.dataset.plan,amount=b.dataset.price;if(!state.apiBase)return alert(`${plan} is ${amount} USDC/month. Connect the payment backend to generate a real checkout.`);try{const r=await fetch(`${state.apiBase.replace(/\/$/,'')}/api/subscription/checkout`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({plan,amount})}),j=await r.json();alert(j.message||JSON.stringify(j))}catch{alert('Payment backend unavailable.')}});
addChat('CryptoPilot bot ready. Try /portfolio or /risk.');render();refreshPrices();