/* GitHub Pages fallback: live-ish cached news + public grant/control data without Worker secrets. */
(()=>{
const hasBackend=()=>{try{return Boolean((JSON.parse(localStorage.getItem('cryptopilot')||'{}').apiBase||'').trim())}catch{return false}};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const get=async path=>{const r=await fetch(path,{cache:'no-store'});if(!r.ok)throw new Error(`Static data unavailable (${r.status})`);return r.json()};
function fmtDate(x){const d=new Date(x);return Number.isNaN(d.getTime())?String(x||''):d.toLocaleString([], {dateStyle:'medium',timeStyle:'short'})}
async function staticNews(){const out=document.querySelector('#newsFeed');if(!out)return;out.innerHTML='<span class="muted">Loading GitHub-cached publisher headlines…</span>';try{const r=await get('./data/news.json'),src=document.querySelector('#newsSource')?.value||'all',items=(r.items||[]).filter(x=>src==='all'||x.sourceId===src);out.innerHTML=`<div class="signal"><strong>GitHub-only news cache</strong><span class="muted">Updated hourly by GitHub Actions${r.fetchedAt?` · last refresh ${esc(fmtDate(r.fetchedAt))}`:''}. Connect the Worker later for server-side queries.</span></div>`+(items.map(x=>`<article class="signal"><div class="row between"><strong>${esc(x.source)}</strong><span class="muted">${esc(fmtDate(x.published))}</span></div><h3 style="margin:8px 0">${esc(x.title)}</h3><a class="btn" target="_blank" rel="noopener noreferrer" href="${esc(x.url)}">Read at ${esc(x.source)}</a></article>`).join('')||'<div class="signal"><span class="muted">The first scheduled feed refresh has not populated headlines yet.</span></div>');const bad=(r.sources||[]).filter(s=>!s.ok);if(bad.length)out.insertAdjacentHTML('beforeend',`<div class="signal"><strong>Partial publisher feed</strong><span class="muted">${esc(bad.map(x=>x.source).join(', '))} could not be refreshed in the latest run.</span></div>`)}catch(e){out.innerHTML=`<div class="signal"><strong class="red">Cached feed unavailable</strong><span class="muted">${esc(e.message)}</span></div>`}}
async function staticGrants(){const list=document.querySelector('#grantList'),pass=document.querySelector('#grantPassport');if(!list)return;try{const r=await get('./data/grants.json');list.innerHTML=`<div class="signal"><strong>Public readiness snapshot · ${esc(r.lastReviewed)}</strong><span class="muted">${esc(r.disclaimer)}</span></div>`+(r.grants||[]).map(g=>`<div class="signal"><div class="row between"><div><strong>${esc(g.ecosystem)} · ${esc(g.program)}</strong><span class="muted">${esc(g.status)} · ${esc(g.funding)}</span></div><div class="score" style="font-size:25px">${Number(g.readiness?.score||0)}%</div></div><div class="bar" style="margin:10px 0"><i style="width:${Number(g.readiness?.score||0)}%"></i></div><span class="muted">Missing: ${esc((g.readiness?.missing||[]).join(', ')||'none in baseline passport')}</span><div style="margin-top:10px"><a class="btn" target="_blank" rel="noopener noreferrer" href="${esc(g.url)}">Official program</a></div></div>`).join('');if(pass)pass.innerHTML=Object.entries(r.passport||{}).map(([k,v])=>`<div class="exchange"><span>${esc(k)}</span><b class="${v?'green':'muted'}">${v?'READY':'GAP'}</b></div>`).join('')}catch(e){list.innerHTML=`<div class="signal"><strong class="red">Grant snapshot unavailable</strong><span class="muted">${esc(e.message)}</span></div>`}}
async function staticControls(){const out=document.querySelector('#instControls');if(!out)return;try{const r=await get('./data/institutional-controls.json');out.innerHTML=(r.controls||[]).map(c=>`<div class="exchange"><div><strong>${esc(c.label)}</strong><div class="muted">${esc(c.id)}</div></div><b class="${c.status==='implemented'?'green':'muted'}">${esc(c.status)}</b></div>`).join('')}catch(e){out.innerHTML=`<span class="muted">${esc(e.message)}</span>`}}
function mount(){if(hasBackend())return;const n=document.querySelector('#newsRefresh');if(n){n.onclick=staticNews;document.querySelector('#newsSource')?.addEventListener('change',staticNews);staticNews()}const g=document.querySelector('#grantRefresh');if(g){g.onclick=staticGrants;staticGrants()}staticControls();const report=document.querySelector('#instReport');if(report)report.innerHTML='<strong>Public controls available</strong><span class="muted">Deploy/connect the Worker and authenticate a wallet for account-specific risk, connector activity and audit exports.</span>'}
document.addEventListener('DOMContentLoaded',mount);
})();
