/* CryptoPilot Hyperliquid Pilot: testnet-only, user-signed, spot-only orders. */
(()=>{
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const MIN_USD=10,MAX_USD=20,DAY_USD=100,MONTH_USD=500;
const read=()=>{try{return JSON.parse(localStorage.getItem('cryptopilot-hl-intents')||'[]')}catch{return []}};
const write=v=>localStorage.setItem('cryptopilot-hl-intents',JSON.stringify(v));
function usage(){const now=Date.now(),rows=read().filter(x=>now-Number(x.t)<32*864e5);write(rows);return {rows,day:rows.filter(x=>now-x.t<864e5).reduce((a,x)=>a+Number(x.usd||0),0),month:rows.filter(x=>now-x.t<30*864e5).reduce((a,x)=>a+Number(x.usd||0),0)}}
let account=null,mods=null;
function addTab(){const tabs=document.querySelector('#tabs'),main=document.querySelector('main');if(!tabs||!main||document.querySelector('#hyperliquid-trade'))return;const b=document.createElement('button');b.className='btn tab';b.textContent='Hyperliquid';b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelector('#hyperliquid-trade').classList.add('active')};tabs.append(b);const s=document.createElement('section');s.className='panel';s.id='hyperliquid-trade';s.innerHTML=`<div class="grid"><div class="card span8"><div class="eyebrow">Testnet · user-signed · spot only</div><h2>Hyperliquid $10–$20 Test Pilot</h2><p class="muted">Connect an EVM wallet, load Hyperliquid testnet spot markets and submit an IOC limit order. CryptoPilot never receives your private key. No mainnet order path is exposed.</p><div class="row" style="gap:8px;flex-wrap:wrap"><button class="btn primary" id="hlConnect">Connect wallet</button><button class="btn" id="hlMarkets">Load testnet spot markets</button></div><div class="signal" id="hlWallet"><span class="muted">Wallet not connected.</span></div><div class="cp-grid" style="margin-top:12px"><div><label class="label">Spot pair</label><select id="hlPair"><option value="">Load spot markets…</option></select></div><div><label class="label">Side</label><select id="hlSide"><option value="buy">Buy</option><option value="sell">Sell</option></select></div><div><label class="label">Limit price (USDC)</label><input class="input" id="hlPrice" type="number" min="0" step="any"></div><div><label class="label">Size (base token)</label><input class="input" id="hlSize" type="number" min="0" step="any"></div></div><div class="signal" id="hlNotional"><strong>$0.00 notional</strong><span class="muted">Allowed test notional: $10.00–$20.00.</span></div><button class="btn primary" id="hlSubmit">Sign testnet order</button><div class="signal" id="hlTradeOut"><span class="muted">Testnet only. No real-money Hyperliquid execution is enabled.</span></div></div><div class="card span4"><h2>Guardrails</h2><div class="signal"><strong>$20 maximum test notional</strong><span class="muted">Computed from price × size.</span></div><div class="signal"><strong>Spot only</strong><span class="muted">Uses 10000 + spot universe index. No perps/leverage/transfer APIs.</span></div><div class="signal"><strong>Every order signed</strong><span class="muted">Your wallet remains final authority.</span></div><div id="hlUsage" class="signal"></div></div></div>`;wire();renderUsage()}
async function loadMods(){if(mods)return mods;const [hl,viem,chains]=await Promise.all([import('https://esm.sh/@nktkas/hyperliquid@0.33.3?bundle'),import('https://esm.sh/viem@2.56.0'),import('https://esm.sh/viem@2.56.0/chains')]);mods={hl,viem,chains};return mods}
async function connect(){const out=document.querySelector('#hlWallet');try{if(!window.ethereum)throw new Error('Install/enable an EVM wallet such as MetaMask.');const {viem,chains}=await loadMods(),accounts=await window.ethereum.request({method:'eth_requestAccounts'});account=accounts?.[0];if(!account)throw new Error('Wallet connection was not approved.');mods.wallet=viem.createWalletClient({account,chain:chains.arbitrum,transport:viem.custom(window.ethereum)});out.innerHTML=`<strong class="green">${esc(account.slice(0,8))}…${esc(account.slice(-6))}</strong><span class="muted">Connected for Hyperliquid testnet signing.</span>`}catch(e){out.innerHTML=`<strong class="red">Not connected</strong><span class="muted">${esc(e.message)}</span>`}}
async function loadMarkets(){const sel=document.querySelector('#hlPair'),out=document.querySelector('#hlTradeOut');try{const r=await fetch('https://api.hyperliquid-testnet.xyz/info',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({type:'spotMeta'})}),j=await r.json();if(!r.ok||!Array.isArray(j?.universe))throw new Error(`spotMeta failed (${r.status})`);sel.innerHTML=j.universe.filter(x=>Number.isInteger(x.index)).slice(0,250).map(x=>`<option value="${x.index}">${esc(x.name||('@'+x.index))} · spot #${x.index}</option>`).join('');out.innerHTML='<span class="green">Hyperliquid testnet spot markets loaded.</span>'}catch(e){out.innerHTML=`<strong class="red">Market load failed</strong><span class="muted">${esc(e.message)}</span>`}}
function calc(){const p=Number(document.querySelector('#hlPrice')?.value||0),s=Number(document.querySelector('#hlSize')?.value||0),n=p*s,el=document.querySelector('#hlNotional');if(el)el.innerHTML=`<strong class="${n>=MIN_USD&&n<=MAX_USD?'green':'red'}">$${Number.isFinite(n)?n.toFixed(2):'0.00'} notional</strong><span class="muted">Allowed: $${MIN_USD.toFixed(2)}–$${MAX_USD.toFixed(2)}.</span>`;return n}
function renderUsage(){const u=usage(),el=document.querySelector('#hlUsage');if(el)el.innerHTML=`<strong>Local test counter</strong><span class="muted">$${u.day.toFixed(2)}/$${DAY_USD} rolling day · $${u.month.toFixed(2)}/$${MONTH_USD} rolling 30 days.</span>`}
async function submit(){const out=document.querySelector('#hlTradeOut');try{if(!account||!mods?.wallet)throw new Error('Connect your wallet first.');const spotIndex=Number(document.querySelector('#hlPair').value),price=Number(document.querySelector('#hlPrice').value),size=Number(document.querySelector('#hlSize').value),notional=price*size,side=document.querySelector('#hlSide').value,u=usage();if(!Number.isInteger(spotIndex)||spotIndex<0)throw new Error('Choose a valid testnet spot market.');if(!Number.isFinite(price)||price<=0||!Number.isFinite(size)||size<=0)throw new Error('Enter a positive price and size.');if(notional<MIN_USD||notional>MAX_USD)throw new Error(`Test order notional must be between $${MIN_USD} and $${MAX_USD}.`);if(u.day+notional>DAY_USD)throw new Error(`Local rolling-day test budget is $${DAY_USD}.`);if(u.month+notional>MONTH_USD)throw new Error(`Local rolling-30-day test budget is $${MONTH_USD}.`);const transport=new mods.hl.HttpTransport({isTestnet:true}),client=new mods.hl.ExchangeClient({transport,wallet:mods.wallet,defaultExpiresAfter:()=>Date.now()+30_000});const payload={orders:[{a:10000+spotIndex,b:side==='buy',p:String(price),s:String(size),r:false,t:{limit:{tif:'Ioc'}}}],grouping:'na'};out.innerHTML='<span class="muted">Waiting for wallet signature / testnet response…</span>';const result=await client.order(payload);write([...u.rows,{t:Date.now(),usd:notional,network:'testnet',spotIndex,side}]);renderUsage();out.innerHTML=`<strong class="green">Testnet responded</strong><pre style="white-space:pre-wrap;word-break:break-word">${esc(JSON.stringify(result,null,2))}</pre>`}catch(e){out.innerHTML=`<strong class="red">Test order not sent / rejected</strong><span class="muted">${esc(e.message)}</span>`}}
function wire(){document.querySelector('#hlConnect')?.addEventListener('click',connect);document.querySelector('#hlMarkets')?.addEventListener('click',loadMarkets);document.querySelector('#hlPrice')?.addEventListener('input',calc);document.querySelector('#hlSize')?.addEventListener('input',calc);document.querySelector('#hlSubmit')?.addEventListener('click',submit)}
document.addEventListener('DOMContentLoaded',addTab);
})();
