/* CryptoPilot intelligence layer: curated news, grant radar, institutional room, chain strategy. */
(()=>{
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const apiBase=()=>{try{return (JSON.parse(localStorage.getItem('cryptopilot')||'{}').apiBase||'').replace(/\/$/,'')}catch{return ''}};
const prod=()=>{try{return JSON.parse(localStorage.getItem('cryptopilot-production')||'{}')}catch{return {}}};
async function api(path){if(!apiBase())throw new Error('Add the deployed Worker URL in Connect first.');const h={};if(prod().session)h.authorization=`Bearer ${prod().session}`;const r=await fetch(apiBase()+path,{headers:h}),j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||j.message||`Request failed (${r.status})`);return j}
function activate(id,button){document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.panel').forEach(x=>x.classList.remove('active'));button.classList.add('active');document.querySelector('#'+id)?.classList.add('active')}
function addTab(id,label,html){const tabs=document.querySelector('#tabs'),main=document.querySelector('main');if(!tabs||!main||document.querySelector(`[data-tab="${id}"]`))return;const b=document.createElement('button');b.className='btn tab';b.dataset.tab=id;b.textContent=label;b.onclick=()=>activate(id,b);tabs.append(b);const s=document.createElement('section');s.className='panel';s.id=id;s.innerHTML=html;main.append(s)}
function mountNews(){addTab('newsroom','News',`<div class="grid"><div class="card span8"><div class="row between"><div><div class="eyebrow">Market intelligence</div><h2>Crypto newsroom</h2></div><div class="row"><select id="newsSource" style="width:auto"><option value="all">All sources</option><option value="coindesk">CoinDesk</option><option value="cointelegraph">Cointelegraph</option><option value="investing">Investing.com</option></select><button class="btn primary" id="newsRefresh">Refresh</button></div></div><p class="muted">Headline + short excerpt feed. Full stories always open at the publisher.</p><div id="newsFeed"><span class="muted">Open this tab and refresh after the Worker is connected.</span></div></div><div class="card span4"><h2>News → signal policy</h2><div class="signal"><strong>No headline can trade directly</strong><span class="muted">News is an input to the evidence score. Price confirmation, portfolio limits, stale-data checks and the risk constitution still gate every action.</span></div><div class="signal"><strong>Source diversity</strong><span class="muted">CoinDesk, Cointelegraph and Investing.com are deliberately shown side-by-side to reduce single-source bias.</span></div></div></div>`);const btn=document.querySelector('#newsRefresh');if(btn)btn.onclick=loadNews}
async function loadNews(){const out=document.querySelector('#newsFeed');if(!out)return;out.innerHTML='<span class="muted">Loading feeds…</span>';try{const src=document.querySelector('#newsSource')?.value||'all',r=await api(`/api/news/curated?source=${encodeURIComponent(src)}&limit=36`);out.innerHTML=(r.items||[]).map(x=>`<article class="signal"><div class="row between"><strong>${esc(x.source)}</strong><span class="muted">${esc(x.published||'')}</span></div><h3 style="margin:8px 0">${esc(x.title)}</h3><p class="muted">${esc(x.summary||'')}</p><a class="btn" target="_blank" rel="noopener noreferrer" href="${esc(x.url)}">Read at ${esc(x.source)}</a></article>`).join('')||'<span class="muted">No items returned.</span>';if((r.sources||[]).some(s=>!s.ok))out.insertAdjacentHTML('afterbegin',`<div class="signal"><strong>Partial feed</strong><span class="muted">${esc(r.sources.filter(s=>!s.ok).map(s=>s.source).join(', '))} is temporarily unavailable; other publishers remain live.</span></div>`)}catch(e){out.innerHTML=`<div class="signal"><strong class="red">News backend unavailable</strong><span class="muted">${esc(e.message)}</span></div>`}}
function mountGrants(){addTab('grants','Grant Radar',`<div class="grid"><div class="card span8"><div class="row between"><div><div class="eyebrow">Non-dilutive capital</div><h2>Grant Radar</h2></div><button class="btn primary" id="grantRefresh">Check readiness</button></div><p class="muted">Tracks major ecosystem programs and scores CryptoPilot against public criteria. A score is preparation guidance, never a guarantee of eligibility or funding.</p><div id="grantList"></div></div><div class="card span4"><h2>Grant passport</h2><div id="grantPassport"><span class="muted">Load the radar to see what is already provable and what still needs shipping.</span></div></div></div>`);document.querySelector('#grantRefresh')?.addEventListener('click',loadGrants)}
async function loadGrants(){const list=document.querySelector('#grantList'),pass=document.querySelector('#grantPassport');if(!list)return;list.innerHTML='<span class="muted">Loading current registry…</span>';try{const r=await api('/api/grants');list.innerHTML=r.grants.map(g=>`<div class="signal"><div class="row between"><div><strong>${esc(g.ecosystem)} · ${esc(g.program)}</strong><span class="muted">${esc(g.status)} · ${esc(g.funding)}</span></div><div class="score" style="font-size:25px">${g.readiness.score}%</div></div><div class="bar" style="margin:10px 0"><i style="width:${g.readiness.score}%"></i></div><span class="muted">Missing: ${esc(g.readiness.missing.join(', ')||'none in baseline passport')}</span><div style="margin-top:10px"><a class="btn" target="_blank" rel="noopener noreferrer" href="${esc(g.url)}">Official program</a></div></div>`).join('');const p=r.passport||{};pass.innerHTML=Object.entries(p).map(([k,v])=>`<div class="exchange"><span>${esc(k)}</span><b class="${v?'green':'muted'}">${v?'READY':'GAP'}</b></div>`).join('')}catch(e){list.innerHTML=`<div class="signal"><strong class="red">Grant backend unavailable</strong><span class="muted">${esc(e.message)}</span></div>`}}
function mountInstitutional(){addTab('institutional','Institutional',`<div class="grid"><div class="card span8"><div class="eyebrow">Due diligence room</div><h2>Institutional readiness</h2><p class="muted">Security controls, risk limits, connector state and auditable activity are exposed without revealing exchange secrets.</p><div id="instControls"></div></div><div class="card span4"><h2>Your risk report</h2><button class="btn primary" id="instLoad">Load authenticated report</button><button class="btn" id="instExport" style="margin-top:8px">Export audit JSON</button><div id="instReport" class="signal"><span class="muted">Wallet login required for account-specific data.</span></div></div></div>`);document.querySelector('#instLoad')?.addEventListener('click',loadInstitutional);document.querySelector('#instExport')?.addEventListener('click',exportAudit);loadControls()}
async function loadControls(){const out=document.querySelector('#instControls');if(!out)return;try{const r=await api('/api/institutional/controls');out.innerHTML=r.controls.map(c=>`<div class="exchange"><div><strong>${esc(c.label)}</strong><div class="muted">${esc(c.id)}</div></div><b class="${c.status==='implemented'?'green':'muted'}">${esc(c.status)}</b></div>`).join('')}catch(e){out.innerHTML=`<span class="muted">${esc(e.message)}</span>`}}
async function loadInstitutional(){const out=document.querySelector('#instReport');try{const r=await api('/api/institutional/report');out.innerHTML=`<strong>24h: ${r.activity24h.orders} orders · $${Number(r.activity24h.notionalUsd).toLocaleString()}</strong><span class="muted">Audit events: ${r.auditEvents}<br>Risk cap: $${Number(r.risk.limits.maxOrderUsd).toLocaleString()} / order<br>Connectors: ${r.connections.map(x=>x.exchange+': '+x.mode).join(', ')||'none'}</span>`}catch(e){out.innerHTML=`<strong class="red">Report unavailable</strong><span class="muted">${esc(e.message)}</span>`}}
async function exportAudit(){try{const r=await api('/api/institutional/audit-export?limit=1000'),blob=new Blob([JSON.stringify(r,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='cryptopilot-audit-export.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}catch(e){alert(e.message)}}
function mountTokenStrategy(){const grid=document.querySelector('#token .grid');if(!grid||document.querySelector('#chainStrategy'))return;const c=document.createElement('div');c.className='card span12';c.id='chainStrategy';c.innerHTML=`<div class="eyebrow">2030 scenario planning · not a token-price forecast</div><h2>CPT chain strategy</h2><div class="plans"><div class="plan hot"><strong>1 · Ethereum ecosystem</strong><div class="price">9.2/10</div><p class="muted">Canonical CPT. Best durability, liquidity and institutional narrative. Prefer Base/L2 for app utility; Ethereum mainnet remains the security/liquidity anchor.</p></div><div class="plan"><strong>2 · Solana</strong><div class="price">8.8/10</div><p class="muted">Best second deployment if CryptoPilot develops high-frequency social/reward activity. Strong low-fee payments and consumer UX.</p></div><div class="plan"><strong>3 · BNB Chain</strong><div class="price">8.1/10</div><p class="muted">Excellent mass-market distribution and EVM compatibility. Add after measurable demand instead of fragmenting CPT liquidity immediately.</p></div><div class="plan"><strong>Grant-specific · TRON</strong><div class="price">7.8/10</div><p class="muted">Worth a TRON-native pilot for agentic payments/DeFi and Builders League alignment, but not as the canonical token today.</p></div></div><div class="signal"><strong>Recommended issuance rule</strong><span class="muted">One canonical supply first. Do not mint independent supplies on multiple chains. Add verified canonical bridging/mint-burn controls only after audits and real cross-chain demand.</span></div>`;grid.append(c)}
document.addEventListener('DOMContentLoaded',()=>{mountNews();mountGrants();mountInstitutional();mountTokenStrategy()});
})();
