/* CryptoPilot production browser layer. Exchange secrets never enter this file. */
(()=>{
const K='cryptopilot-production',p=Object.assign({session:'',wallet:''},JSON.parse(localStorage.getItem(K)||'{}')),saveP=()=>localStorage.setItem(K,JSON.stringify(p));
const base=()=>{try{return (JSON.parse(localStorage.getItem('cryptopilot')||'{}').apiBase||'').replace(/\/$/,'')}catch{return ''}};
async function api(path,opt={}){if(!base())throw new Error('Add the deployed Worker URL in Connect first.');const h=new Headers(opt.headers||{});if(p.session)h.set('authorization',`Bearer ${p.session}`);if(opt.body&&!h.has('content-type'))h.set('content-type','application/json');const r=await fetch(base()+path,{...opt,headers:h}),j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||j.message||`Request failed (${r.status})`);return j}
const short=a=>a?`${a.slice(0,6)}…${a.slice(-4)}`:'Not connected';
function authView(){const s=document.querySelector('#walletState'),b=document.querySelector('#walletConnectBtn');if(s)s.textContent=p.session?`Authenticated · ${short(p.wallet)}`:'Not authenticated';if(b)b.textContent=p.session?'Reconnect wallet':'Connect wallet'}
async function connectWallet(){if(!window.ethereum)throw new Error('No EIP-1193 wallet found. Reown/WalletConnect can plug into this same provider flow once a Project ID is configured.');const [address]=await ethereum.request({method:'eth_requestAccounts'}),c=await api('/api/auth/wallet/challenge',{method:'POST',body:JSON.stringify({address})}),signature=await ethereum.request({method:'personal_sign',params:[c.message,address]}),v=await api('/api/auth/wallet/verify',{method:'POST',body:JSON.stringify({address,message:c.message,signature})});p.session=v.token;p.wallet=v.user.walletAddress;saveP();authView();return v}
async function verify(){if(!p.session)return;try{const m=await api('/api/auth/me');p.wallet=m.user.walletAddress;saveP()}catch{p.session='';p.wallet='';saveP()}authView()}
function mount(){
 const grid=document.querySelector('#connect .grid');if(grid&&!document.querySelector('#prodAuth')){const c=document.createElement('div');c.className='card span6';c.id='prodAuth';c.innerHTML='<div class="eyebrow">Production identity</div><h2>Wallet authentication</h2><p class="muted">Sign a login message. It authenticates your app session only and does not authorize a trade or transfer.</p><div class="signal"><strong id="walletState">Not authenticated</strong><span class="muted">Injected wallets work now; the backend is Reown / WalletConnect-ready.</span></div><div class="row"><button class="btn primary" id="walletConnectBtn">Connect wallet</button><button class="btn" id="walletLogoutBtn">Forget session</button></div><div id="prodStatus" class="muted" style="margin-top:10px"></div>';grid.append(c);c.querySelector('#walletConnectBtn').onclick=async()=>{const s=c.querySelector('#prodStatus');try{s.textContent='Waiting for signature…';await connectWallet();s.className='green';s.textContent='Wallet session authenticated.'}catch(e){s.className='red';s.textContent=e.message}};c.querySelector('#walletLogoutBtn').onclick=()=>{p.session='';p.wallet='';saveP();authView()}}
 const ag=document.querySelector('#autopilot .grid');if(ag&&!document.querySelector('#backtestCard')){const c=document.createElement('div');c.className='card span6';c.id='backtestCard';c.innerHTML='<div class="eyebrow">Historical validation</div><h2>Backtest before automation</h2><p class="muted">Deterministic SMA baseline using Coinbase public candles. It is a sanity check, not a forecast.</p><div class="row"><select id="btProduct" style="flex:1"><option>BTC-USD</option><option>ETH-USD</option><option>SOL-USD</option></select><select id="btG" style="flex:1"><option value="3600">1 hour</option><option value="21600">6 hours</option><option value="86400">1 day</option></select></div><div class="row"><div style="flex:1"><label class="label">Fast SMA</label><input class="input" id="btF" type="number" value="10"></div><div style="flex:1"><label class="label">Slow SMA</label><input class="input" id="btS" type="number" value="30"></div></div><button class="btn primary" id="btRun" style="margin-top:12px">Run backtest</button><div class="signal" id="btOut"><span class="muted">No run yet.</span></div>';ag.append(c);c.querySelector('#btRun').onclick=async()=>{const o=c.querySelector('#btOut');o.innerHTML='<span class="muted">Running…</span>';try{const r=await api('/api/backtest',{method:'POST',body:JSON.stringify({product:c.querySelector('#btProduct').value,granularity:Number(c.querySelector('#btG').value),fast:Number(c.querySelector('#btF').value),slow:Number(c.querySelector('#btS').value),capital:10000,feeBps:25})});o.innerHTML=`<strong>${r.returnPct}% strategy return</strong><span class="muted">Buy/hold ${r.buyHoldPct}% · max drawdown ${r.maxDrawdownPct}% · ${r.trades} trades</span>`}catch(e){o.innerHTML=`<strong class="red">Unavailable</strong><span class="muted">${e.message}</span>`}}}
 const dex=document.querySelector('#connect .grid .card:nth-child(2)');if(dex&&!document.querySelector('#dexSellToken')){dex.insertAdjacentHTML('beforeend','<hr style="border:0;border-top:1px solid var(--line);margin:18px 0"><h3>User-signed 0x route</h3><p class="muted">Use token contract addresses and base-unit amount. CryptoPilot gets the route; your wallet signs it.</p><input class="input" id="dexChain" value="8453" placeholder="chainId"><input class="input" id="dexSellToken" style="margin-top:8px" placeholder="sellToken"><input class="input" id="dexBuyToken" style="margin-top:8px" placeholder="buyToken"><input class="input" id="dexAmount" style="margin-top:8px" placeholder="sellAmount"><div class="row" style="margin-top:10px"><button class="btn" id="dexQuote">Get quote</button><button class="btn primary" id="dexSign" disabled>Sign transaction</button></div><div class="muted" id="dexOut" style="margin-top:8px"></div>');let q=null;dex.querySelector('#dexQuote').onclick=async()=>{const o=dex.querySelector('#dexOut');try{if(!p.wallet)throw new Error('Authenticate a wallet first.');const qs=new URLSearchParams({chainId:dex.querySelector('#dexChain').value,sellToken:dex.querySelector('#dexSellToken').value.trim(),buyToken:dex.querySelector('#dexBuyToken').value.trim(),sellAmount:dex.querySelector('#dexAmount').value.trim(),taker:p.wallet});q=await api(`/api/dex/quote?${qs}`);const spender=q?.issues?.allowance?.spender;o.textContent=`Quote: ${q.buyAmount||'?'} buy units. Allowance target: ${spender||'none required'}`;dex.querySelector('#dexSign').disabled=!q?.transaction?.to}catch(e){q=null;dex.querySelector('#dexSign').disabled=true;o.textContent=e.message}};dex.querySelector('#dexSign').onclick=async()=>{const o=dex.querySelector('#dexOut');try{if(!window.ethereum||!q?.transaction)throw new Error('Wallet or quote missing.');if(q?.issues?.allowance?.spender)throw new Error('Approval required first. Approve only the exact 0x allowance spender shown above, never the execution/Settler address.');const t=q.transaction,tx={from:p.wallet,to:t.to,data:t.data,value:t.value?`0x${BigInt(t.value).toString(16)}`:'0x0'};if(t.gas)tx.gas=`0x${BigInt(t.gas).toString(16)}`;const hash=await ethereum.request({method:'eth_sendTransaction',params:[tx]});o.textContent=`Wallet submitted ${hash}`}catch(e){o.textContent=e.message}}}
 document.querySelectorAll('.pay').forEach(old=>{if(old.dataset.production)return;const b=old.cloneNode(true);b.dataset.production='1';old.replaceWith(b);b.onclick=async()=>{try{if(!p.session)throw new Error('Connect your wallet before starting a paid subscription.');const r=await api('/api/subscription/checkout',{method:'POST',body:JSON.stringify({plan:b.dataset.plan})});if(!r.url)throw new Error('No hosted payment URL returned.');location.href=r.url}catch(e){alert(e.message)}}});
 const learn=document.querySelector('#learnBtn');if(learn&&!learn.dataset.production){learn.dataset.production='1';learn.addEventListener('click',async()=>{if(!p.session)return;try{await api('/api/risk/profile',{method:'POST',body:JSON.stringify({style:document.querySelector('#style')?.value,networth:Number(document.querySelector('#networth')?.value),drawdown:Number(document.querySelector('#drawdown')?.value),singleCap:Number(document.querySelector('#singleCap')?.value)})})}catch(e){console.warn(e.message)}})}
 const kill=document.querySelector('#killBtn');if(kill&&!kill.dataset.production){kill.dataset.production='1';kill.addEventListener('click',async()=>{if(!p.session)return;try{await api('/api/risk/pause',{method:'POST',body:JSON.stringify({reason:'Emergency stop from web app'})})}catch(e){console.warn(e.message)}})}authView();
}
function ticker(){if(!('WebSocket'in window))return;let ws,timer;const go=()=>{ws=new WebSocket('wss://advanced-trade-ws.coinbase.com');ws.onopen=()=>{ws.send(JSON.stringify({type:'subscribe',channel:'ticker',product_ids:['BTC-USD','ETH-USD','SOL-USD']}));const s=document.querySelector('#priceStatus');if(s)s.textContent='Coinbase live stream'};ws.onmessage=e=>{try{const m=JSON.parse(e.data),ticks=[];(m.events||[]).forEach(v=>Array.isArray(v.tickers)&&ticks.push(...v.tickers));for(const t of ticks){const coin=String(t.product_id||'').split('-')[0],px=Number(t.price);if(!['BTC','ETH','SOL'].includes(coin)||!Number.isFinite(px))continue;try{if(typeof state!=='undefined'&&state.portfolio?.[coin]){state.portfolio[coin].price=px;if(typeof save==='function')save()}}catch{}}if(ticks.length){try{if(typeof renderAssets==='function')renderAssets();if(typeof portfolioValue==='function'){const n=document.querySelector('#portfolioValue');if(n)n.textContent=new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(portfolioValue())}}catch{}}}catch{}};ws.onclose=()=>{clearTimeout(timer);timer=setTimeout(go,4000)};ws.onerror=()=>ws.close()};go();addEventListener('beforeunload',()=>{clearTimeout(timer);ws?.close()})}
document.addEventListener('DOMContentLoaded',()=>{mount();verify();ticker()});
})();
