/* Runtime hardening for CryptoPilot 2.3+. Loaded after v23.js. */
(()=>{
const LIMIT={order:5,day:10,month:100,baseUsdc:'0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913'};
const read=()=>{try{return JSON.parse(localStorage.getItem('cryptopilot-micro-intents')||'[]')}catch{return []}};
const write=v=>localStorage.setItem('cryptopilot-micro-intents',JSON.stringify(v));
function usage(){const now=Date.now(),rows=read().filter(x=>now-Number(x.t)<32*864e5);write(rows);return {rows,day:rows.filter(x=>now-x.t<864e5).reduce((a,x)=>a+Number(x.usd||0),0),month:rows.filter(x=>now-x.t<30*864e5).reduce((a,x)=>a+Number(x.usd||0),0)}}
function render(){const u=usage(),el=document.querySelector('#microUsage');if(!el)return;const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);el.innerHTML=`<strong>${money(u.day)} / ${money(LIMIT.day)} today</strong><span class="muted">${money(u.month)} / ${money(LIMIT.month)} rolling 30 days · records launch intents, not confirmed fills.</span><div class="cp-progress" style="margin-top:9px"><i style="width:${Math.min(100,u.month/LIMIT.month*100)}%"></i></div>`}
function replaceMicro(){const old=document.querySelector('#microOpen');if(!old||old.dataset.hardened)return;const btn=old.cloneNode(true);btn.dataset.hardened='true';old.replaceWith(btn);btn.addEventListener('click',()=>{const usd=Number(document.querySelector('#microUsd')?.value||0),u=usage();if(!Number.isFinite(usd)||usd<1||usd>LIMIT.order)return alert(`Use an amount from $1 to $${LIMIT.order}.`);if(u.day+usd>LIMIT.day)return alert(`Local daily MicroTrade budget is $${LIMIT.day}.`);if(u.month+usd>LIMIT.month)return alert(`Local rolling-30-day MicroTrade budget is $${LIMIT.month}.`);write([...u.rows,{t:Date.now(),usd}]);render();const url=`https://app.uniswap.org/#/swap?chain=base&theme=dark&field=input&value=${encodeURIComponent(usd)}&inputCurrency=${LIMIT.baseUsdc}&outputCurrency=ETH`;window.open(url,'_blank','noopener,noreferrer')})}
function fixAgentCopy(){for(const el of document.querySelectorAll('.cp-code')){if(el.textContent.includes('openaiDeveloperDocs'))el.textContent='cd CryptoPilot\ncodex\n# AGENTS.md contains CryptoPilot project rules.\n# For current plugin/MCP configuration, use the official OpenAI developer documentation:\n# https://developers.openai.com/';}}
function addInvestorDocs(){const form=document.querySelector('#eoiForm');if(!form||document.querySelector('#eoiDocLinks'))return;const d=document.createElement('div');d.id='eoiDocLinks';d.className='signal';d.innerHTML='<strong>Read before submitting</strong><span class="muted">The checkbox requests a later NDA process; it does not itself create a binding NDA.</span><div class="row" style="margin-top:9px"><a class="btn" target="_blank" rel="noopener" href="https://github.com/coolcryptomaniac/CryptoPilot/blob/main/docs/INVESTOR_DISCLOSURE.md">Risk & full disclosure</a><a class="btn" target="_blank" rel="noopener" href="https://github.com/coolcryptomaniac/CryptoPilot/blob/main/docs/NDA_DATA_ROOM_PROCESS.md">NDA/data-room process</a><a class="btn" href="mailto:founder@roamwise.co.in?subject=CryptoPilot%20investor%20data-room">Email founder</a></div>';form.prepend(d)}
function organizeNav(){const circles=document.querySelector('[data-tab="social"]'),sharing=document.querySelector('[data-tab="socialconnect"]');if(circles)circles.textContent='Circles';if(sharing)sharing.textContent='Share & Login';const sel=document.querySelector('#cpTheme'),header=document.querySelector('.top .row');if(sel){sel.setAttribute('aria-label','CryptoPilot visual theme');const labels={"liquid-neon":"Theme · Liquid Neon","akatsuki-storm":"Theme · Akatsuki Storm","default":"Theme · Classic"};[...sel.options].forEach(o=>o.textContent=labels[o.value]||o.textContent);if(header&&!header.contains(sel))header.insertBefore(sel,header.firstChild)}}
function copyFallback(text){const ta=document.createElement('textarea');ta.value=text;ta.setAttribute('readonly','');ta.style.cssText='position:fixed;left:-9999px;top:0';document.body.append(ta);ta.select();let ok=false;try{ok=document.execCommand('copy')}catch{}ta.remove();return ok}
async function copyText(text){try{if(navigator.clipboard&&window.isSecureContext){await navigator.clipboard.writeText(text);return true}}catch{}return copyFallback(text)}
function hardenSharing(){document.querySelectorAll('[data-share]').forEach(a=>{a.rel='noopener noreferrer'});const copy=document.querySelector('#shareCopy');if(copy&&!copy.dataset.hardened){const b=copy.cloneNode(true);b.dataset.hardened='true';copy.replaceWith(b);b.addEventListener('click',async()=>alert(await copyText(location.href.split('#')[0])?'CryptoPilot link copied.':'Copy was blocked by this browser.'))}const native=document.querySelector('#shareNative');if(native&&!native.dataset.hardened){const b=native.cloneNode(true);b.dataset.hardened='true';native.replaceWith(b);b.addEventListener('click',async()=>{const url=location.href.split('#')[0];if(navigator.share){try{await navigator.share({title:'CryptoPilot',text:'AI crypto intelligence and micro-trading',url});return}catch(e){if(e?.name==='AbortError')return}}alert(await copyText(url)?'Link copied. Paste it into Instagram or any social app.':'Use your browser share menu to share this page.')})}}
function markPanels(){for(const id of ['microtrade','socialconnect','investor-eoi','agentdev','hyperliquid-trade']){const p=document.querySelector('#'+id);if(p)p.classList.add('cp-dynamic-panel')}}
document.addEventListener('DOMContentLoaded',()=>setTimeout(()=>{replaceMicro();fixAgentCopy();addInvestorDocs();organizeNav();hardenSharing();markPanels();render()},0));
})();
