export const GRANTS_LAST_REVIEWED='2026-09-01';
export const GRANTS=[
{id:'tether-developer-grants',ecosystem:'USDT / Tether',program:'Tether Developer Grants',status:'open',funding:'Current technical tasks roughly $1,500–$4,000 each in USD₮ or Bitcoin; Tether states no cap on total payouts',url:'https://tether.io/news/tether-launches-developer-grants-program-to-fund-local-first-ai-and-payments-infrastructure/',focus:['usdt','wdk','local-ai','payments','wallets'],criteria:['workingDemo','usdtIntegration','tetherWdkPrototype','openSource','technicalDeliverable','security']},
{id:'tether-wdk-partner',ecosystem:'USDT / Tether',program:'Tether WDK Project / Technology Partner',status:'applications open / selective',funding:'Technical support, early API/SDK access and potential co-marketing; not a guaranteed grant',url:'https://docs.wdk.tether.io/overview/partner-program/',focus:['wallets','self-custody','ai-agents','payments','enterprise'],criteria:['workingDemo','tetherWdkPrototype','usdtIntegration','productionPath','security','team']},
{id:'tron-builders-league',ecosystem:'TRON',program:'TRON Builders League',status:'open/rolling',funding:'Up to $5,000,000',url:'https://trondao.org/tron-builders-league',focus:['ai','payments','defi','social','cross-chain'],criteria:['workingDemo','tronIntegration','milestones','community','security']},
{id:'solana-foundation',ecosystem:'Solana',program:'Solana Foundation Grants & Funding',status:'rolling',funding:'Milestone-based grants / convertible grants; amount varies; ecosystem microgrants also available',url:'https://solana.org/grants-funding',focus:['public-goods','payments','defi','tooling'],criteria:['workingDemo','solanaIntegration','openSource','milestones','publicGood','budget']},
{id:'circle-grants',ecosystem:'USDC / Circle / Arc',program:'Circle Developer Grants',status:'application window currently closed; monitor reopening',funding:'Milestone-based USDC funding; amount varies',url:'https://www.circle.com/grant',focus:['usdc','payments','stablecoins','arc','agents','rwa'],criteria:['workingDemo','circleIntegration','arcIntegration','productionPath','metrics','security']},
{id:'base-batches-004',ecosystem:'Base',program:'Base Batches 004',status:'open until 2026-09-09',funding:'$100,000 investment from Base Ecosystem Fund for selected teams',url:'https://www.base.org/batches',focus:['trading','payments','agents','financing','asset-issuance'],criteria:['workingDemo','baseIntegration','team','businessModel','pitch','productionPath']},
{id:'base-ecosystem-fund',ecosystem:'Base',program:'Base Ecosystem Fund',status:'rolling investment applications',funding:'Pre-seed/seed strategic investment; amount varies',url:'https://www.base.org/ecosystem-fund',focus:['onchain-finance','trading','payments','agents'],criteria:['workingDemo','baseIntegration','team','traction','businessModel','metrics']},
{id:'bnb-mvb',ecosystem:'BNB Chain',program:'Most Valuable Builder (MVB)',status:'rolling admission',funding:'Selective investment + 4-week accelerator support',url:'https://www.bnbchain.org/en/programs/mvb',focus:['defi','socialfi','consumer','middleware','ai'],criteria:['workingDemo','bnbIntegration','tokenomics','businessModel','team','traction']},
{id:'ethereum-esp',ecosystem:'Ethereum',program:'Ethereum Foundation Ecosystem Support Program',status:'open RFPs / wishlist',funding:'Milestone grants; amount varies',url:'https://esp.ethereum.foundation/applicants',focus:['open-source','public-goods','security','tooling','research'],criteria:['openSource','publicGood','ethereumIntegration','milestones','security','technicalDeliverable']},
{id:'stellar-scf-46',ecosystem:'Stellar',program:'Stellar Community Fund — Build',status:'SCF #46 submission deadline 2026-11-08',funding:'Up to $150,000 in XLM for Build awards',url:'https://communityfund.stellar.org/awards',focus:['payments','defi','infrastructure','integration','global-finance'],criteria:['workingDemo','stellarIntegration','budget','milestones','team','productionPath']},
{id:'starknet-seed',ecosystem:'Starknet',program:'Starknet Seed Grants',status:'open',funding:'Up to $25,000 in STRK',url:'https://www.starknet.io/grants/seed-grants/',focus:['early-stage','apps','integration','self-custody'],criteria:['workingDemo','starknetIntegration','community','milestones','team']},
{id:'starknet-growth',ecosystem:'Starknet',program:'Starknet Growth Grants',status:'open',funding:'$25,000 to $1,000,000 in STRK',url:'https://www.starknet.io/grants/growth-grants/',focus:['growth','integration','bitcoin','next-billion','apps'],criteria:['workingDemo','starknetIntegration','traction','metrics','team','productionPath']},
{id:'celo-prezenti-s3',ecosystem:'Celo',program:'Prezenti Season 3',status:'open through 2026-12-29',funding:'Frontier, Anchor and Boost grant pools; program-specific awards',url:'https://forum.celo.org/t/prezenti-season-3-is-open-frontier-anchor-and-boost-grants-for-celo/13714',focus:['ai-agents','payments','minipay','transactions','tvl'],criteria:['workingDemo','celoIntegration','agenticPayments','metrics','milestones','impact']},
{id:'xrpl-ecosystem',ecosystem:'XRPL / Ripple',program:'RippleX Ecosystem Programs',status:'fall accelerator programs open; grants calls vary/monitor',funding:'Milestone grants, accelerators and possible investment consideration; varies',url:'https://xrplgrants.org/',focus:['defi','rwa','payments','trade-finance','ai'],criteria:['workingDemo','xrplIntegration','rwaIntegration','codeAccess','team','productionPath']},
{id:'arbitrum-open-house',ecosystem:'Arbitrum',program:'Open House Singapore 2026',status:'open / current season',funding:'$415,000 total prizes & grants',url:'https://blog.arbitrum.foundation/builders-block-023-415k-in-prizes-at-open-house-singapore-apply-now/',focus:['apps','agentic-payments','defi','institutional'],criteria:['workingDemo','arbitrumIntegration','traction','team','pitch']},
{id:'avalanche-build-games',ecosystem:'Avalanche',program:'Build Games 2026',status:'seasonal / monitor',funding:'$1,000,000 prize pool; $100,000 grand prize',url:'https://build.avax.network/build-games',focus:['apps','defi','consumer','crypto-native'],criteria:['workingDemo','avalancheIntegration','execution','team','longTerm']},
{id:'near-funding',ecosystem:'NEAR',program:'NEAR Ecosystem Funding',status:'rolling / multiple programs',funding:'Grants and protocol rewards; varies',url:'https://www.near.org/funding',focus:['tooling','apps','ai','public-goods'],criteria:['workingDemo','nearIntegration','metrics','openSource','milestones']},
{id:'optimism-grants',ecosystem:'Optimism / Superchain',program:'Superchain Grants / Retro Funding',status:'program-specific / monitor',funding:'Program-specific; historically multi-million OP pools',url:'https://atlas.optimism.io/',focus:['superchain','apps','public-goods','growth'],criteria:['workingDemo','superchainIntegration','metrics','impact','openSource']},
{id:'ton-support',ecosystem:'TON',program:'TON Ecosystem Support',status:'program-specific / TON Console transition',funding:'Program-specific',url:'https://builders.ton.org/',focus:['consumer','social','payments','telegram'],criteria:['workingDemo','tonIntegration','traction','team','metrics']},
{id:'dfinity-grants',ecosystem:'Internet Computer',program:'DFINITY Developer Grants',status:'temporarily closed / monitor reopening',funding:'Developer grants; amount varies',url:'https://dfinity.org/grants-overview',focus:['deai','tooling','infrastructure','integrations','apps'],criteria:['workingDemo','icpIntegration','openSource','milestones','technicalDeliverable']},
{id:'cardano-catalyst',ecosystem:'Cardano',program:'Catalyst Pilot 2026',status:'2026 application window closed; monitor next round',funding:'2.5M ADA total pilot; 50k–200k ADA per selected project in 2026 round',url:'https://projectcatalyst.io/apply',focus:['oracles','stablecoins','programmable-tokens','identity'],criteria:['workingDemo','cardanoIntegration','metrics','milestones','productionPath']}
];

export const PROJECT_PASSPORT={
  workingDemo:true,publicDeployment:true,openSource:true,ci:true,security:true,securityAudit:false,smartContractAudit:false,technicalDeliverable:true,milestones:true,budget:false,
  team:false,community:true,metrics:false,traction:false,businessModel:true,tokenomics:true,productionPath:true,productionWorker:false,d1Deployed:false,publicGood:true,pitch:false,impact:false,longTerm:false,execution:false,
  legalEntity:false,legalMemo:false,kycKyb:false,sanctionsScreening:false,privacyTerms:false,incidentResponse:false,codeAccess:true,
  ethereumIntegration:true,baseIntegration:false,usdcIntegration:true,circleIntegration:true,arcIntegration:false,usdtIntegration:true,tetherWdkPrototype:true,localFirst:false,agenticPayments:true,
  bnbIntegration:false,solanaIntegration:false,tronIntegration:false,stellarIntegration:false,starknetIntegration:false,celoIntegration:false,xrplIntegration:false,arbitrumIntegration:false,avalancheIntegration:false,nearIntegration:false,superchainIntegration:false,tonIntegration:false,icpIntegration:false,cardanoIntegration:false,
  rwaIntegration:true,predictionData:true,developerApi:true,institutionalControls:true,roamwisePartner:true
};
export function readiness(grant,passport=PROJECT_PASSPORT){const c=grant.criteria||[],done=c.filter(k=>passport[k]);return {score:c.length?Math.round(done.length/c.length*100):0,met:done,missing:c.filter(k=>!passport[k])};}
export function grantRadar({ecosystem='',status=''}={}){let grants=GRANTS;if(ecosystem)grants=grants.filter(g=>g.ecosystem.toLowerCase().includes(ecosystem.toLowerCase()));if(status)grants=grants.filter(g=>g.status.toLowerCase().includes(status.toLowerCase()));return {lastReviewed:GRANTS_LAST_REVIEWED,disclaimer:'Readiness scoring is not eligibility or a funding guarantee. Programs, deadlines, KYC requirements and funding terms change; re-check the official program before applying.',passport:PROJECT_PASSPORT,grants:grants.map(g=>({...g,readiness:readiness(g)}))};}
