export const GRANTS_LAST_REVIEWED='2026-09-01';
export const GRANTS=[
{id:'tron-builders-league',ecosystem:'TRON',program:'TRON Builders League',status:'open/rolling',funding:'Up to $5,000,000',url:'https://trondao.org/tron-builders-league',focus:['ai','payments','defi','social','cross-chain'],criteria:['workingDemo','tronIntegration','milestones','community','security']},
{id:'solana-foundation',ecosystem:'Solana',program:'Solana Foundation Grants & Funding',status:'rolling',funding:'Milestone-based grants / convertible grants; amount varies',url:'https://solana.org/grants-funding',focus:['public-goods','payments','defi','tooling'],criteria:['workingDemo','solanaIntegration','openSource','milestones','publicGood']},
{id:'circle-grants',ecosystem:'USDC / Circle',program:'Circle Developer Grants',status:'reopening / monitor',funding:'Amount varies',url:'https://www.circle.com/blog/announcing-the-first-circle-grant-recipients-in-2026',focus:['usdc','payments','stablecoins','arc','agents'],criteria:['workingDemo','usdcIntegration','productionPath','metrics','security']},
{id:'bnb-mvb',ecosystem:'BNB Chain',program:'Most Valuable Builder (MVB)',status:'rolling admission',funding:'Selective investment + accelerator support',url:'https://www.bnbchain.org/en/programs/mvb',focus:['defi','socialfi','consumer','middleware','ai'],criteria:['workingDemo','bnbIntegration','tokenomics','businessModel','team']},
{id:'ethereum-esp',ecosystem:'Ethereum',program:'Ethereum Foundation Ecosystem Support Program',status:'open RFPs / wishlist',funding:'Milestone grants; amount varies',url:'https://esp.ethereum.foundation/applicants',focus:['open-source','public-goods','security','tooling','research'],criteria:['openSource','publicGood','ethereumIntegration','milestones','security']},
{id:'arbitrum-open-house',ecosystem:'Arbitrum',program:'Open House Singapore 2026',status:'open / current season',funding:'$415,000 total prizes & grants',url:'https://blog.arbitrum.foundation/builders-block-023-415k-in-prizes-at-open-house-singapore-apply-now/',focus:['apps','agentic-payments','defi','institutional'],criteria:['workingDemo','arbitrumIntegration','traction','team','pitch']},
{id:'avalanche-build-games',ecosystem:'Avalanche',program:'Build Games 2026',status:'seasonal / monitor',funding:'$1,000,000 prize pool; $100,000 grand prize',url:'https://build.avax.network/build-games',focus:['apps','defi','consumer','crypto-native'],criteria:['workingDemo','avalancheIntegration','execution','team','longTerm']},
{id:'near-funding',ecosystem:'NEAR',program:'NEAR Ecosystem Funding',status:'rolling / multiple programs',funding:'Grants and protocol rewards; varies',url:'https://www.near.org/funding',focus:['tooling','apps','ai','public-goods'],criteria:['workingDemo','nearIntegration','metrics','openSource','milestones']},
{id:'optimism-grants',ecosystem:'Optimism / Superchain',program:'Superchain Grants / Retro Funding',status:'transitioning',funding:'Program-specific; historic pools in millions of OP',url:'https://atlas.optimism.io/',focus:['superchain','apps','public-goods','growth'],criteria:['workingDemo','superchainIntegration','metrics','impact','openSource']},
{id:'ton-support',ecosystem:'TON',program:'TON Ecosystem Support',status:'transitioning to TON Console',funding:'Program-specific',url:'https://builders.ton.org/',focus:['consumer','social','payments','telegram'],criteria:['workingDemo','tonIntegration','traction','team','metrics']}
];
export const PROJECT_PASSPORT={workingDemo:true,openSource:true,security:true,milestones:true,team:false,community:true,metrics:false,traction:false,businessModel:true,tokenomics:true,productionPath:true,publicGood:true,pitch:false,ethereumIntegration:true,usdcIntegration:true,bnbIntegration:false,solanaIntegration:false,tronIntegration:false,arbitrumIntegration:false,avalancheIntegration:false,nearIntegration:false,superchainIntegration:false,tonIntegration:false};
export function readiness(grant,passport=PROJECT_PASSPORT){const c=grant.criteria||[],done=c.filter(k=>passport[k]);return {score:c.length?Math.round(done.length/c.length*100):0,met:done,missing:c.filter(k=>!passport[k])};}
export function grantRadar({ecosystem='',status=''}={}){let grants=GRANTS;if(ecosystem)grants=grants.filter(g=>g.ecosystem.toLowerCase().includes(ecosystem.toLowerCase()));if(status)grants=grants.filter(g=>g.status.toLowerCase().includes(status.toLowerCase()));return {lastReviewed:GRANTS_LAST_REVIEWED,disclaimer:'Readiness scoring is not eligibility or a funding guarantee. Programs change and applications require program-specific review.',passport:PROJECT_PASSPORT,grants:grants.map(g=>({...g,readiness:readiness(g)}))};}
