export function integrationRegistry(env={}){return [
  {id:'tether-wdk',category:'wallets/stablecoins',name:'Tether WDK + USDT',status:'prototype-ready',mode:'self-custodial',configured:Boolean(env.USDT_TOKEN_ADDRESS),notes:'WDK module example + verified EVM USDT merchant checkout; no server-side seed custody.'},
  {id:'circle-cctp-v2',category:'stablecoins/crosschain',name:'Circle CCTP V2',status:'adapter-ready',mode:'read/status',configured:true,notes:'CCTP V2 attestation/status endpoint; use Arc/Circle integrations for grant alignment.'},
  {id:'uniswap',category:'dex',name:'Uniswap',status:'backend-free-microtrade-live',mode:'user-signed/custom-link',configured:true,notes:'Official prefilled swap link for $1–$5 user-signed experiments; wallet and Uniswap remain final transaction authority.'},
  {id:'hyperliquid',category:'dex/perps/market-data',name:'Hyperliquid',status:'public-data-live',mode:'public-market-data-only',configured:true,notes:'Public allMids feed is integrated. Authenticated trading is deliberately not used for the $1–$5 rail because venue-side minimum order constraints apply.'},
  {id:'pyth',category:'oracle/market-data',name:'Pyth Core',status:'adapter-ready',mode:'read-only',configured:Boolean(env.PYTH_API_KEY),notes:'Uses post-Aug-26-2026 authenticated upgraded Hermes API.'},
  {id:'kalshi',category:'prediction-signals',name:'Kalshi',status:'live-public-market-api',mode:'market-data-only',configured:true,notes:'Public prediction-market data is an optional signal input. CryptoPilot does not expose authenticated Kalshi trading.'},
  {id:'centrifuge',category:'rwa',name:'Centrifuge',status:'live-public-api',mode:'read-only',configured:true,notes:'Public GraphQL RWA pool/token data; suitable for institutional RWA discovery.'},
  {id:'defillama',category:'defi-analytics',name:'DefiLlama',status:'live-public-api',mode:'read-only',configured:true,notes:'Protocol/TVL discovery and risk context.'},
  {id:'0x',category:'dex',name:'0x Swap API',status:'integrated',mode:'user-signed',configured:Boolean(env.ZEROX_API_KEY),notes:'Quote routing only; user wallet signs.'},
  {id:'tempo',category:'payments/agentic-commerce',name:'Tempo',status:'integration-target',mode:'stablecoin-native-payments',configured:false,notes:'Track payments-first primitives: stablecoin gas, memos, fee sponsorship, smart accounts/passkeys and agentic microtransactions.'},
  {id:'coinbase',category:'cex',name:'Coinbase Advanced Trade',status:'integrated',mode:'paper/test/live/pilot',configured:true},
  {id:'binance',category:'cex',name:'Binance Spot',status:'integrated',mode:'paper/testnet/live/pilot',configured:true},
  {id:'kraken',category:'cex',name:'Kraken Spot',status:'integrated',mode:'paper/live/pilot',configured:true},
  {id:'robinhood',category:'cex',name:'Robinhood Crypto',status:'regional',mode:'paper/live/pilot',configured:true,notes:'Availability depends on user jurisdiction.'},
  {id:'google-identity',category:'identity',name:'Google Identity Services',status:'frontend-ready',mode:'profile/onboarding-only',configured:false,notes:'Optional easy social profile. Wallet-signature authentication remains the financial authorization boundary.'},
  {id:'web3auth-privy',category:'identity/wallets',name:'Web3Auth / Privy',status:'integration-target',mode:'embedded-wallet/social-login',configured:false,notes:'Optional social/email wallet onboarding after operator project IDs and security review.'},
  {id:'alchemy',category:'wallet-infra',name:'Alchemy Wallet APIs',status:'integration-target',mode:'smart-wallets/session-keys',configured:Boolean(env.ALCHEMY_API_KEY)},
  {id:'jupiter',category:'solana-dex',name:'Jupiter',status:'integration-target',mode:'user-signed',configured:Boolean(env.JUPITER_API_KEY)},
  {id:'lifi',category:'crosschain',name:'LI.FI',status:'integration-target',mode:'user-signed',configured:Boolean(env.LIFI_API_KEY)},
  {id:'codex',category:'developer-agents',name:'OpenAI Codex',status:'repo-ready',mode:'AGENTS.md + OpenAPI/MCP-ready',configured:true,notes:'Repository rules keep financial safety gates and secret handling explicit.'},
  {id:'claude-code',category:'developer-agents',name:'Claude Code',status:'repo-ready',mode:'CLAUDE.md + MCP-ready',configured:true,notes:'Repository rules mirror the same test/live-trading/token-sale safety constraints.'},
  {id:'roamwise',category:'partner',name:'RoamWise',status:'founder-ecosystem-partner',mode:'referral/api',configured:true,notes:'Travel planning and travel-utility partner reference.'}
];}

export async function centrifugePools(limit=20){
  const n=Math.max(1,Math.min(100,Number(limit)||20)),query=`query CryptoPilotPools { pools(where:{isActive:true,name_not:null},limit:${n}) { items { id name centrifugeId isActive tokens { items { id name symbol totalIssuance tokenPrice } } } } }`;
  const r=await fetch('https://api.centrifuge.io',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({query})}),j=await r.json();if(!r.ok||j.errors)throw new Error(`Centrifuge API failed: ${j.errors?.[0]?.message||r.status}`);return j.data?.pools?.items||[];
}
export async function defiLlamaProtocols(limit=25){const r=await fetch('https://api.llama.fi/protocols'),j=await r.json();if(!r.ok||!Array.isArray(j))throw new Error('DefiLlama protocols unavailable');return j.sort((a,b)=>Number(b.tvl||0)-Number(a.tvl||0)).slice(0,Math.max(1,Math.min(100,Number(limit)||25))).map(x=>({name:x.name,symbol:x.symbol,category:x.category,chains:x.chains,tvl:x.tvl,url:x.url,change_1d:x.change_1d,change_7d:x.change_7d}));}
export async function pythLatest(env,ids=[]){if(!env.PYTH_API_KEY)throw new Error('PYTH_API_KEY is not configured');const clean=ids.filter(Boolean).slice(0,20);if(!clean.length)throw new Error('At least one Pyth feed id is required');const qs=new URLSearchParams();for(const id of clean)qs.append('ids[]',id);const r=await fetch(`https://pyth.dourolabs.app/hermes/v2/updates/price/latest?${qs}`,{headers:{authorization:`Bearer ${env.PYTH_API_KEY}`}}),j=await r.json();if(!r.ok)throw new Error(`Pyth request failed (${r.status})`);return j;}
export async function kalshiMarkets(_env,{limit=20,seriesTicker='',status='open'}={}){const q=new URLSearchParams({limit:String(Math.max(1,Math.min(100,Number(limit)||20)))});if(seriesTicker)q.set('series_ticker',seriesTicker);if(status)q.set('status',status);const r=await fetch(`https://external-api.kalshi.com/trade-api/v2/markets?${q}`),j=await r.json();if(!r.ok)throw new Error(`Kalshi public market-data request failed (${r.status})`);return j;}
export async function circleCctpStatus({sourceDomain,txHash,testnet=false}={}){if(sourceDomain===undefined||!/^0x[0-9a-fA-F]{64}$/.test(String(txHash||'')))throw new Error('sourceDomain and transaction hash are required');const host=testnet?'https://iris-api-sandbox.circle.com':'https://iris-api.circle.com',r=await fetch(`${host}/v2/messages/${encodeURIComponent(sourceDomain)}?transactionHash=${encodeURIComponent(txHash)}`),j=await r.json();if(!r.ok)throw new Error(`Circle CCTP request failed (${r.status})`);return j;}
export function roamwisePartner(){return {name:'RoamWise',url:'https://www.roamwise.co.in/?utm_source=cryptopilot&utm_medium=partner&utm_campaign=founder_ecosystem',integrationIdeas:['stablecoin-paid travel plans','CryptoPilot subscriber travel benefit','API referral bundle','crypto-friendly trip intelligence'],disclaimer:'RoamWise is presented as a founder ecosystem/partner reference; no financial relationship is implied unless separately configured.'};}
