import { openWalletConnection, subscribeWalletProvider, subscribeWalletAccount } from './wallet-connect.js';
const BASE_CHAIN_ID='0x2105', BASE_USDC='0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913', API='https://cryptopilot-api.founder-f53.workers.dev';
const $=s=>document.querySelector(s), connectBtn=$('#connectBtn'),switchBtn=$('#switchBtn'),refreshBtn=$('#refreshBtn'),tradeBtn=$('#tradeBtn'),walletStatus=$('#walletStatus'),tradeStatus=$('#tradeStatus'),usdcBalance=$('#usdcBalance'),riskCheck=$('#riskCheck'),custodyCheck=$('#custodyCheck');
let provider=null,account=null,chainId=null,balance=0,selectedAmount=1,approvalPending=false;
const short=a=>a?`${a.slice(0,6)}…${a.slice(-4)}`:'', pad=a=>a.toLowerCase().replace(/^0x/,'').padStart(64,'0'), hex=n=>'0x'+BigInt(n).toString(16);
function status(el,message,kind='warn'){el.className=`status ${kind}`;el.textContent=message}
function update(){tradeBtn.textContent=`Quote & review $${selectedAmount} swap`;tradeBtn.disabled=approvalPending||!(provider&&account&&chainId===BASE_CHAIN_ID&&balance>=selectedAmount&&riskCheck.checked&&custodyCheck.checked);if(!account)return status(tradeStatus,'Connect a wallet to start.');if(chainId!==BASE_CHAIN_ID)return status(tradeStatus,'Switch your wallet to Base.');if(balance<selectedAmount)return status(tradeStatus,`You need at least ${selectedAmount} USDC on Base.`);if(!riskCheck.checked||!custodyCheck.checked)return status(tradeStatus,'Accept both disclosures before continuing.');status(tradeStatus,'Ready to request a quote. Wallet approval is always required.','good')}
async function syncWallet(){if(!provider){account=null;chainId=null;balance=0;usdcBalance.textContent='—';switchBtn.disabled=true;refreshBtn.disabled=true;status(walletStatus,'Not connected.');return update()}try{const accounts=await provider.request({method:'eth_accounts'});account=accounts?.[0]||null;chainId=await provider.request({method:'eth_chainId'});switchBtn.disabled=!account;refreshBtn.disabled=!account;status(walletStatus,account?`${short(account)} connected${chainId===BASE_CHAIN_ID?' on Base':' on another network'}.`:'Select a wallet to connect.',account&&chainId===BASE_CHAIN_ID?'good':'warn');await refreshBalance()}catch(e){status(walletStatus,e?.message||'Unable to read wallet.','bad')}}
async function refreshBalance(){if(!provider||!account){balance=0;usdcBalance.textContent='—';return update()}try{chainId=await provider.request({method:'eth_chainId'});if(chainId!==BASE_CHAIN_ID){balance=0;usdcBalance.textContent='Switch to Base';return update()}const raw=await provider.request({method:'eth_call',params:[{to:BASE_USDC,data:'0x70a08231'+pad(account)},'latest']});balance=Number(BigInt(raw))/1e6;usdcBalance.textContent=balance.toLocaleString(undefined,{maximumFractionDigits:6})}catch(e){balance=0;usdcBalance.textContent='Unavailable';status(tradeStatus,'Could not read Base USDC balance.','bad')}update()}
async function switchBase(){if(!provider)return openWalletConnection();try{await provider.request({method:'wallet_switchEthereumChain',params:[{chainId:BASE_CHAIN_ID}]})}catch(e){if(e?.code===4902)await provider.request({method:'wallet_addEthereumChain',params:[{chainId:BASE_CHAIN_ID,chainName:'Base',nativeCurrency:{name:'Ether',symbol:'ETH',decimals:18},rpcUrls:['https://mainnet.base.org'],blockExplorerUrls:['https://basescan.org']}]});else return status(walletStatus,e?.message||'Network switch cancelled.','bad')}await syncWallet()}
async function quote(){const u=new URL(`${API}/api/dex/quote`);u.searchParams.set('sellAmount',String(selectedAmount*1e6));u.searchParams.set('taker',account);const r=await fetch(u);const q=await r.json();if(!r.ok)throw Error(q?.message||q?.reason||q?.error||`Quote failed (${r.status})`);return q}
async function waitReceipt(hash){for(let i=0;i<40;i++){const r=await provider.request({method:'eth_getTransactionReceipt',params:[hash]});if(r){if(BigInt(r.status)!==1n)throw Error('Approval reverted on chain');return}await new Promise(resolve=>setTimeout(resolve,3000))}throw Error('Approval still pending. Check your wallet before retrying.')}
async function execute(){if(tradeBtn.disabled)return;const signingProvider=provider,signingAccount=account;approvalPending=true;tradeBtn.disabled=true;try{status(tradeStatus,'Requesting 0x quote…');let q=await quote();if(provider!==signingProvider||account!==signingAccount)throw Error('Wallet changed; start again.');const spender=q?.issues?.allowance?.spender;const fee=q?.fees?.integratorFee?.amount;const feeUSDC=fee?Number(fee)/1e6:selectedAmount*.005;const output=q?.buyAmount?`${(Number(q.buyAmount)/1e18).toPrecision(6)} ETH`:'ETH';if(!confirm(`Review live swap\nSell: ${selectedAmount} USDC\nEstimated output: ${output}\nCryptoPilot fee: ${feeUSDC.toFixed(6)} USDC\nOther network and 0x fees may apply.\n\nContinue to wallet approval?`))return status(tradeStatus,'Cancelled. Nothing signed.');if(spender){if(!/^0x[a-f\d]{40}$/i.test(spender))throw Error('Invalid approval spender');const amount=BigInt(q.sellAmount||selectedAmount*1e6);if(amount!==BigInt(selectedAmount*1e6))throw Error('Unexpected quote amount');status(tradeStatus,`Approve exactly ${selectedAmount} USDC for ${short(spender)}. Check your wallet.`);const hash=await signingProvider.request({method:'eth_sendTransaction',params:[{from:signingAccount,to:BASE_USDC,data:'0x095ea7b3'+pad(spender)+amount.toString(16).padStart(64,'0')}]});status(tradeStatus,'Waiting for approval confirmation…');await waitReceipt(hash);q=await quote()}if(provider!==signingProvider||account!==signingAccount||await provider.request({method:'eth_chainId'})!==BASE_CHAIN_ID)throw Error('Wallet or network changed; start again.');if(q?.issues?.allowance?.spender)throw Error('Approval not yet reflected in quote; retry after confirmation.');const tx=q?.transaction;if(!/^0x[a-f\d]{40}$/i.test(tx?.to||'')||!/^0x[a-f\d]+$/i.test(tx?.data||''))throw Error('Invalid executable transaction');if(!confirm(`Final transaction\nSell ${selectedAmount} USDC\nTo: ${tx.to}\nCryptoPilot fee: ${feeUSDC.toFixed(6)} USDC\n\nConfirm in your wallet?`))return status(tradeStatus,'Swap cancelled.');const hash=await signingProvider.request({method:'eth_sendTransaction',params:[{from:signingAccount,to:tx.to,data:tx.data,value:hex(tx.value||0),...(tx.gas?{gas:hex(tx.gas)}:{})}]});status(tradeStatus,`Transaction submitted: ${hash}. Check BaseScan for settlement.`,'good');await refreshBalance()}catch(e){status(tradeStatus,e?.message||'Transaction failed or cancelled.','bad')}finally{approvalPending=false;update()}}
subscribeWalletProvider(p=>{provider=p;void syncWallet()});subscribeWalletAccount(()=>{void syncWallet()});
connectBtn.addEventListener('click',()=>openWalletConnection().catch(e=>status(walletStatus,e?.message||'Could not open wallet selection.','bad')));
switchBtn.addEventListener('click',switchBase);refreshBtn.addEventListener('click',refreshBalance);tradeBtn.addEventListener('click',execute);riskCheck.addEventListener('change',update);custodyCheck.addEventListener('change',update);
document.querySelectorAll('[data-amount]').forEach(b=>b.addEventListener('click',()=>{selectedAmount=Number(b.dataset.amount);document.querySelectorAll('[data-amount]').forEach(x=>x.classList.toggle('active',x===b));update()}));
update();
