const BASE_CHAIN_ID='0x2105';
const BASE_USDC='0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913';
const API='https://cryptopilot-api.founder-f53.workers.dev';
const ERC20_BALANCE_OF='0x70a08231';
const ERC20_APPROVE='0x095ea7b3';
const $=s=>document.querySelector(s),connectBtn=$('#connectBtn'),switchBtn=$('#switchBtn'),refreshBtn=$('#refreshBtn'),tradeBtn=$('#tradeBtn'),walletStatus=$('#walletStatus'),tradeStatus=$('#tradeStatus'),usdcBalance=$('#usdcBalance'),riskCheck=$('#riskCheck'),custodyCheck=$('#custodyCheck');
let provider=null,account=null,selectedAmount=1,balance=0,chainId=null;
const shortAddress=a=>a?`${a.slice(0,6)}…${a.slice(-4)}`:'';
const padAddress=a=>a.toLowerCase().replace(/^0x/,'').padStart(64,'0');
const padUint=n=>BigInt(n).toString(16).padStart(64,'0');
function setWalletStatus(t,k=''){walletStatus.className=`status ${k}`.trim();walletStatus.textContent=t}
function setTradeStatus(t,k='warn'){tradeStatus.className=`status ${k}`.trim();tradeStatus.textContent=t}
function getProvider(){return window.ethereum||null}
async function connect(){provider=getProvider();if(!provider){setWalletStatus('No injected EVM wallet found. Open this page inside Coinbase Wallet or MetaMask.','bad');return}try{const a=await provider.request({method:'eth_requestAccounts'});account=a?.[0]||null;chainId=await provider.request({method:'eth_chainId'});if(!account)throw new Error('No account returned');switchBtn.disabled=false;refreshBtn.disabled=false;setWalletStatus(`${shortAddress(account)} connected${chainId===BASE_CHAIN_ID?' on Base':' on another network'}.`,chainId===BASE_CHAIN_ID?'good':'warn');await refreshBalance();updateTradeState()}catch(e){setWalletStatus(e?.message||'Wallet connection was cancelled.','bad')}}
async function switchToBase(){if(!provider)return connect();try{await provider.request({method:'wallet_switchEthereumChain',params:[{chainId:BASE_CHAIN_ID}]})}catch(e){if(e?.code===4902)await provider.request({method:'wallet_addEthereumChain',params:[{chainId:BASE_CHAIN_ID,chainName:'Base',nativeCurrency:{name:'Ether',symbol:'ETH',decimals:18},rpcUrls:['https://mainnet.base.org'],blockExplorerUrls:['https://basescan.org']}]});else return setWalletStatus(e?.message||'Could not switch network.','bad')}chainId=await provider.request({method:'eth_chainId'});await refreshBalance();setWalletStatus(`${shortAddress(account)} connected on Base.`,'good');updateTradeState()}
async function refreshBalance(){if(!provider||!account){usdcBalance.textContent='—';return}try{chainId=await provider.request({method:'eth_chainId'});if(chainId!==BASE_CHAIN_ID){balance=0;usdcBalance.textContent='Switch to Base';return updateTradeState()}const raw=await provider.request({method:'eth_call',params:[{to:BASE_USDC,data:ERC20_BALANCE_OF+padAddress(account)},'latest']});balance=Number(BigInt(raw))/1e6;usdcBalance.textContent=balance.toLocaleString(undefined,{maximumFractionDigits:6});updateTradeState()}catch{balance=0;usdcBalance.textContent='Unavailable';setTradeStatus('Could not read Base USDC balance.','bad')}}
function updateTradeState(){const ok=account&&chainId===BASE_CHAIN_ID&&riskCheck.checked&&custodyCheck.checked&&balance>=selectedAmount;tradeBtn.textContent=`Quote & review $${selectedAmount} swap`;tradeBtn.disabled=!ok;if(!account)return setTradeStatus('Connect a wallet to start.');if(chainId!==BASE_CHAIN_ID)return setTradeStatus('Switch your wallet to Base.');if(balance<selectedAmount)return setTradeStatus(`You need at least ${selectedAmount} USDC on Base.`);if(!riskCheck.checked||!custodyCheck.checked)return setTradeStatus('Accept both disclosures before continuing.');setTradeStatus('Ready. CryptoPilot will request a 0x quote with a disclosed 0.50% CryptoPilot fee.','good')}
async function getQuote(){const sellAmount=String(Math.round(selectedAmount*1e6));const u=new URL(`${API}/api/dex/quote`);u.searchParams.set('sellAmount',sellAmount);u.searchParams.set('taker',account);const r=await fetch(u);const q=await r.json();if(!r.ok)throw new Error(q?.message||q?.reason||q?.error||`Quote failed (${r.status})`);return q}
async function approveIfNeeded(q){const spender=q?.issues?.allowance?.spender;if(!spender)return;if(!/^0x[a-fA-F0-9]{40}$/.test(spender))throw new Error('0x returned an invalid allowance spender');const allowanceAmount=q?.issues?.allowance?.actual?BigInt(q.sellAmount||Math.round(selectedAmount*1e6)):BigInt(q.sellAmount||Math.round(selectedAmount*1e6));setTradeStatus(`Wallet approval required for ${shortAddress(spender)}. Review it carefully.`,'warn');await provider.request({method:'eth_sendTransaction',params:[{from:account,to:BASE_USDC,data:ERC20_APPROVE+padAddress(spender)+padUint(allowanceAmount)}]});}
async function executeTrade(){if(tradeBtn.disabled)return;tradeBtn.disabled=true;try{setTradeStatus('Requesting secured 0x quote…','warn');let q=await getQuote();const fee=q?.fees?.integratorFee?.amount;const feeUsdc=fee?Number(fee)/1e6:selectedAmount*0.005;const output=q?.buyAmount?`${(Number(q.buyAmount)/1e18).toPrecision(6)} ETH`:'ETH';if(!confirm(`Review CryptoPilot live swap\n\nSell: ${selectedAmount} USDC\nEstimated output: ${output}\nCryptoPilot fee: ${feeUsdc.toFixed(6)} USDC (0.50%)\nSlippage limit: 1.00%\n\nYour wallet will still show every approval and transaction before signing. Continue?`)){setTradeStatus('Trade cancelled. Nothing was signed.','warn');return}if(q?.issues?.allowance?.spender){await approveIfNeeded(q);setTradeStatus('Approval submitted. Refreshing executable quote…','warn');q=await getQuote()}const tx=q?.transaction;if(!tx?.to||!tx?.data)throw new Error('0x did not return an executable transaction');setTradeStatus('Final transaction ready. Confirm only if your wallet details match.','warn');const hash=await provider.request({method:'eth_sendTransaction',params:[{from:account,to:tx.to,data:tx.data,value:tx.value||'0x0',gas:tx.gas?`0x${BigInt(tx.gas).toString(16)}`:undefined}]});setTradeStatus(`Submitted: ${hash.slice(0,10)}… Check BaseScan for settlement and fee receipt.`,'good');await refreshBalance()}catch(e){setTradeStatus(e?.message||'Trade failed or was cancelled.','bad')}finally{updateTradeState()}}
document.querySelectorAll('[data-amount]').forEach(b=>b.addEventListener('click',()=>{selectedAmount=Number(b.dataset.amount);document.querySelectorAll('[data-amount]').forEach(x=>x.classList.toggle('active',x===b));updateTradeState()}));
connectBtn.addEventListener('click',connect);switchBtn.addEventListener('click',switchToBase);refreshBtn.addEventListener('click',refreshBalance);riskCheck.addEventListener('change',updateTradeState);custodyCheck.addEventListener('change',updateTradeState);tradeBtn.addEventListener('click',executeTrade);
if(window.ethereum){window.ethereum.on?.('accountsChanged',async a=>{account=a?.[0]||null;await connect()});window.ethereum.on?.('chainChanged',async id=>{chainId=id;await refreshBalance();if(account)setWalletStatus(`${shortAddress(account)} connected${id===BASE_CHAIN_ID?' on Base':' on another network'}.`,id===BASE_CHAIN_ID?'good':'warn')})}
