const json=(data,status=200)=>new Response(JSON.stringify(data,null,2),{status,headers:{'content-type':'application/json','access-control-allow-origin':'*','access-control-allow-headers':'content-type,authorization','access-control-allow-methods':'GET,POST,OPTIONS'}});
const te=new TextEncoder();
async function hmacHex(secret,message){const k=await crypto.subtle.importKey('raw',te.encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);const sig=await crypto.subtle.sign('HMAC',k,te.encode(message));return [...new Uint8Array(sig)].map(b=>b.toString(16).padStart(2,'0')).join('')}
async function sha256(data){return new Uint8Array(await crypto.subtle.digest('SHA-256',data))}
function b64ToBytes(s){const bin=atob(s);return Uint8Array.from(bin,c=>c.charCodeAt(0))}
function bytesToB64(bytes){let s='';bytes.forEach(b=>s+=String.fromCharCode(b));return btoa(s)}
async function krakenSign(path,nonce,body,secret){const hash=await sha256(te.encode(nonce+body)),p=te.encode(path),msg=new Uint8Array(p.length+hash.length);msg.set(p);msg.set(hash,p.length);const key=await crypto.subtle.importKey('raw',b64ToBytes(secret),{name:'HMAC',hash:'SHA-512'},false,['sign']);return bytesToB64(new Uint8Array(await crypto.subtle.sign('HMAC',key,msg)))}
async function coinbaseSandboxOrder(o){const body={client_order_id:o.client_order_id||crypto.randomUUID(),product_id:o.product_id||'BTC-USD',side:(o.side||'BUY').toUpperCase(),order_configuration:o.order_configuration||{market_market_ioc:{quote_size:String(o.quote_size||'10')}}};const r=await fetch('https://api-sandbox.coinbase.com/api/v3/brokerage/orders',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});return{status:r.status,data:await r.json()}}
async function binanceOrder(env,o){if(!env.BINANCE_API_KEY||!env.BINANCE_API_SECRET)throw new Error('Binance credentials not configured');const endpoint=env.BINANCE_TESTNET==='true'?'https://testnet.binance.vision':'https://api.binance.com';const p=new URLSearchParams({symbol:o.symbol,side:o.side,type:o.type||'MARKET',timestamp:String(Date.now())});if(o.quoteOrderQty)p.set('quoteOrderQty',String(o.quoteOrderQty));if(o.quantity)p.set('quantity',String(o.quantity));p.set('signature',await hmacHex(env.BINANCE_API_SECRET,p.toString()));const r=await fetch(`${endpoint}/api/v3/order`,{method:'POST',headers:{'X-MBX-APIKEY':env.BINANCE_API_KEY,'content-type':'application/x-www-form-urlencoded'},body:p});return{status:r.status,data:await r.json()}}
async function krakenOrder(env,o){if(!env.KRAKEN_API_KEY||!env.KRAKEN_API_SECRET)throw new Error('Kraken credentials not configured');const path='/0/private/AddOrder',nonce=String(Date.now()*1000),p=new URLSearchParams({nonce,ordertype:o.type||'market',type:(o.side||'buy').toLowerCase(),volume:String(o.volume),pair:o.pair}),body=p.toString(),sig=await krakenSign(path,nonce,body,env.KRAKEN_API_SECRET);const r=await fetch('https://api.kraken.com'+path,{method:'POST',headers:{'API-Key':env.KRAKEN_API_KEY,'API-Sign':sig,'content-type':'application/x-www-form-urlencoded'},body});return{status:r.status,data:await r.json()}}
async function dexQuote(env,u){if(!env.ZEROX_API_KEY)throw new Error('0x API key not configured');const qs=new URLSearchParams(u.searchParams),r=await fetch(`https://api.0x.org/swap/allowance-holder/quote?${qs}`,{headers:{'0x-api-key':env.ZEROX_API_KEY,'0x-version':'v2'}});return{status:r.status,data:await r.json()}}
async function gdelt(q){const u=new URL('https://api.gdeltproject.org/api/v2/doc/doc');u.searchParams.set('query',q||'crypto');u.searchParams.set('mode','ArtList');u.searchParams.set('format','json');u.searchParams.set('maxrecords','20');const r=await fetch(u);return{status:r.status,data:await r.json()}}
function riskProfile(x){const style={Conservative:27,Balanced:50,Aggressive:72}[x.style]??50;let n=style+(Number(x.drawdown||18)-18)*.65+(Number(x.singleCap||28)-28)*.35-(Number(x.lessRiskClicks||0)*4);if(Number(x.networth||0)<20000)n-=6;if(Number(x.networth||0)>500000)n+=3;return Math.max(15,Math.min(82,Math.round(n)))}
async function telegram(env,body){if(!env.TELEGRAM_BOT_TOKEN)return json({ok:false,error:'Telegram bot token not configured'},503);const msg=body.message;if(!msg?.chat?.id)return json({ok:true});const t=(msg.text||'').trim();let answer='CryptoPilot: /status, /risk, /pause. Live trading commands are disabled by default.';if(t==='/status')answer='CryptoPilot backend online. Exchange execution remains policy-gated.';if(t==='/pause')answer='Pause request received. Persisted user-level pausing requires D1/KV in production.';await fetch(`https://api.telegram.org/bot${env.TELEGRAM_BOT_TOKEN}/sendMessage`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({chat_id:msg.chat.id,text:answer})});return json({ok:true})}
export default{async fetch(request,env){if(request.method==='OPTIONS')return json({ok:true});const u=new URL(request.url);try{if(u.pathname==='/api/health')return json({ok:true,service:'CryptoPilot Worker',mode:env.ENABLE_LIVE_TRADING==='true'?'live-enabled':'paper-first'});if(u.pathname==='/api/connectors')return json({connectors:{Coinbase:{configured:!!env.COINBASE_API_KEY,sandbox:'implemented/no-auth static sandbox',production:'JWT adapter pending'},Binance:{configured:!!env.BINANCE_API_KEY,testnet:env.BINANCE_TESTNET==='true',execution:'implemented'},Kraken:{configured:!!env.KRAKEN_API_KEY,execution:'implemented'},'Robinhood Crypto':{configured:!!env.ROBINHOOD_API_KEY,execution:'adapter scaffold; US availability only'},'0x DEX':{configured:!!env.ZEROX_API_KEY,execution:'quote implemented; user wallet signs'}}});if(u.pathname==='/api/news'){const x=await gdelt(u.searchParams.get('q')||'bitcoin OR ethereum OR crypto');return json(x.data,x.status)}if(u.pathname==='/api/risk/profile'&&request.method==='POST')return json({risk:riskProfile(await request.json())});if(u.pathname==='/api/dex/quote'){const x=await dexQuote(env,u);return json(x.data,x.status)}if(u.pathname==='/api/order/coinbase-sandbox'&&request.method==='POST'){const x=await coinbaseSandboxOrder(await request.json());return json(x.data,x.status)}if(u.pathname==='/api/order/binance'&&request.method==='POST'){if(env.ENABLE_LIVE_TRADING!=='true')return json({ok:false,error:'Live trading disabled. Use Binance testnet/paper mode first.'},403);const x=await binanceOrder(env,await request.json());return json(x.data,x.status)}if(u.pathname==='/api/order/kraken'&&request.method==='POST'){if(env.ENABLE_LIVE_TRADING!=='true')return json({ok:false,error:'Live trading disabled.'},403);const x=await krakenOrder(env,await request.json());return json(x.data,x.status)}if(u.pathname==='/api/subscription/checkout'&&request.method==='POST'){const b=await request.json();if(!env.COINBASE_PAYMENT_BEARER)return json({ok:false,message:`${b.plan} is ${b.amount} USDC/month. Coinbase Payment Acceptance credentials are not configured yet.`},503);return json({ok:false,message:'Payment credential detected; complete merchant/operator onboarding before charging customers.'},501)}if(u.pathname==='/api/telegram/webhook'&&request.method==='POST')return telegram(env,await request.json());return json({error:'not found'},404)}catch(e){return json({error:e.message||String(e)},500)}}};